version: '3'

services:
  mini-ecommerce-stag:
    image: zakariawahyu/go-mini-ecommerce:stag
    container_name: mini-ecommerce-stag
    environment:
      - PORT=4545
    networks:
      - traefik-proxy
    restart: always
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mini-ecommerce-stag.rule=Host(`ecommerce-stag.zakariawahyu.com`)"
      - "traefik.http.routers.mini-ecommerce-stag.entrypoints=web"
      - "traefik.http.services.mini-ecommerce-stag.loadbalancer.server.port=4545"

networks:
  traefik-proxy:
    external: true
